### ISSUE TITLE
[FR]: Reduced tarif and sales price for PV production

### ISSUE THREAD

**Issue by JensenNick** [MTrab/stromligning#23]
### Describe the feature you wish to make a request for

First of all super work MTrab! Thanks! A couple of suggestions / requests / ideas...

1) The option to choose not to include the transport tariff (I believe it's called) in order to have the price with "reduced tariff" (reduceret el afgift) which would be useful for those who have electricity as main energy source or an agreement for charging their EV which includes reduced tarif.

2) Option to just get the spot price (sorry if I missed it) including the option to add cost. Would be useful in order to be able to calculate the sales price for solar PV production.

### Describe alternatives you've considered

Energi Data Service :-)

**Comment by MTrab** [comment]
The spotprice sensor is already there

**Comment by JensenNick** [comment]
In DK the sales price is always the spotprice minus tarifs where one of the tarifs is the feed-in tarif you pay the vendor/company you've chosen to sell your production to (produktionsleverandør). I was thinking that at least the three other tarifs would be available since they are only regulated on a yearly basis.
![2024-11-04_15-00-24](https://github.com/user-attachments/assets/4a12d687-18ad-40a7-9b43-5872a6c83b30)

**Comment by MTrab** [comment]
I know of systemtariff, nettariff and elafgift

That's the ONLY thing in the API besides the spot prices and the extra fees from the electricity company - hence the need to create a template sensor for this. There is, as far as I know, no API for this information.

**Comment by JensenNick** [comment]
It's a mess :-)... and your work makes this manageable. Thanks again!

**Comment by MTrab** [comment]
Is it okay to close this issue, as the requested values aren't available in the API?

**Comment by JensenNick** [comment]
Feel free to close the issue. I'm just thinking that this can't be far from doable, but I have no idea about what is accessible via the API source. If you would be interested in adding this I could explain how the tariffs are built up and who / where to find the information. It's very minor tariffs so not a first priority task I guess.
