### ISSUE TITLE
[FR]: Input for Cheapest Energy Hours

### ISSUE THREAD

**Issue by JensenNick** [MTrab/stromligning#25]
### Describe the feature you wish to make a request for

Would be useful with a sensor with the prices for today and tomorrow structured as a list in two attributes in order for Strømligning to be used as input for Cheapest Energy Hours by TheFez [https://github.com/TheFes/cheapest-energy-hours](url)

**Comment by MTrab** [comment]
I will not make this change, but I am already working on a similar template for this integration

**Comment by MTrab** [comment]
Copy the `custom_templates/FindCheapestPrice.jinja` to the `custom_templates` directory in your config folder (if it doesn't exist then create the folder)
Reload Home Assistant and use the Jinja template by inserting the example below in a template sensor helper

```
{% from 'FindCheapestPeriod.jinja' import FindCheapestPeriod%}
{% set earliestStartTime = now() %}
{% set latestStartTime = now() + timedelta(days=2) %}
{% set periodLength = timedelta(hours=3) %}
{{ FindCheapestPeriod(earliestStartTime , latestStartTime , periodLength, false) }}
```

This will result in a sensor showing the cheapest 3 hours within the known prices

**Comment by JensenNick** [comment]
Thanks! I'm looking for a bit more complex lookup abilities (some of the functions in Cheapest Energy Hours I'd like to use are split hours, most expensive hours and is now). I'll find a solution :-).
