### ISSUE TITLE
Prices showing doesnt seem to reflect the actual prices 

### ISSUE THREAD

**Issue by amejer** [MTrab/stromligning#38]
### Describe the issue

Hi Mtrab,

Thanks for your integration - seems to work fine but the prices seems to be off, or at least differs from actual prices. 

Currently i have my "Min Strøm" app, to chekc prices - i have reduced tariffs since i have a Heat Pump.

At the time of writing the prices in Stromligning is 2,39,- DKK and the prices in Min Strøm is 1,41,-

Will there be an opportunity to implement the reduced tariffs for customers like me who has Heat Pump or am i just not seeing something obvious? :-) 

### What version of Home Assistant Core has the issue?

core-2024.11.2

### What type of installation are you running?

Home Assistant OS

**Comment by MTrab** [comment]
The reduced tariffs could be made using a template sensor.
As for now there's no plans for implementing this in the integration as it seems redundant
