### ISSUE TITLE
strømpris er ikke kompatibel med EV smart Charge 

### ISSUE THREAD

**Issue by AndersV209** [MTrab/stromligning#39]
### Describe the issue

hvis jeg skifter pris sensor fra Energi data service til denne i EV smart charge interagration i Home assistant. så står den bare og venter på elpris, det ser ud til at data for i priser i morgen mangler på sensoren, den har kun priser for idag? 

### What version of Home Assistant Core has the issue?

core-2024.11.2

### What type of installation are you running?

Home Assistant OS

### Additional information

forventet format https://github.com/jonasbkarlsson/ev_smart_charging/wiki/Price-sensor

**Comment by MTrab** [comment]
Korrekt - denne integration kan ikke bruges med EV Smart Charge, da denne integration ligger sig mere op af design guides end EDS og Nordpool gør.
Dvs sensors fremfor attributes.

Priserne for i morgen ligger som attributes `binary_sensor.stromligning_tomorrow_available_vat`
