### ISSUE TITLE
Manglende El udbyder...måske

### ISSUE THREAD

**Issue by Bo1967** [MTrab/stromligning#40]
### Describe the issue

Har jysk energi, men har ikke i puldown mulighed for at vælge "Variabel strøm med klima"

### What version of Home Assistant Core has the issue?

2024.11.2

### What type of installation are you running?

Home Assistant Core

**Comment by MTrab** [comment]
Er den i listen på strømligning.dk?

**Comment by Bo1967** [comment]
Ja og nej. Der står noget i infofeltet om klimatilvalg, men ikke valgbar fra oversigten. Så er det nok ikke en bug :-D

**Comment by MTrab** [comment]
Umiddelbart ikke en bug, da den heller ikke er i dropdown ved Stromligning.dk
